# .github/workflows/strava-snapshot.yml
name: Build Strava Monthly Snapshots

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Remove/disable any "npm ci" or "npm i" steps

      - name: Show package.json (debug)
        run: |
          echo "----- package.json head -----"
          sed -n '1,120p' package.json || true
          echo "----- package.json tail -----"
          tail -n 60 package.json || true

      - name: Run snapshot builder
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: node scripts/fetch_strava.js

      - name: Commit & push snapshots
        run: |
          git config user.name "gh-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/activities
          if ! git diff --cached --quiet; then
            git commit -m "chore: update Strava snapshots [skip ci]"
            git push
          else
            echo "No changes."
          fi
